"""Markdown report (Phase 5): an honest, readable side-by-side comparison.

Presentation only: every number comes from Phase 4's ``TaskSuiteMetrics``
/ ``CalibrationReport`` / ``classify_failure`` computed over this run's
traces — nothing is re-derived or re-interpreted here beyond formatting and
explicitly flagging thin data (small categories, low-statistics ECE).

The centerpiece is :func:`build_honest_conclusion`: the project's founding
idea is that "the best number in the table" is often NOT the right choice
for a given use (strongest overall model vs cheapest vs fastest). That
divergence is computed programmatically from the actual numbers of THIS
run and phrased with a fixed parameterized template — never generated by
an LLM call, which would be both ironic and untrustworthy for a tool whose
whole point is honest reporting.
"""

from __future__ import annotations

from pathlib import Path

from agentalyze.analysis.calibration import CalibrationReport, compute_calibration_report
from agentalyze.analysis.failure_taxonomy import FailureTag, classify_failure
from agentalyze.analysis.metrics import CategoryMetrics, TaskSuiteMetrics
from agentalyze.orchestration.suite_runner import SuiteRunResult
from agentalyze.runner.trace import RunOutcome, RunTrace
from agentalyze.tasks.models import TaskCategory

#: Categories with fewer tasks than this are explicitly marked as
#: small-sample in the report instead of being presented with the same
#: confidence as well-populated ones.
SMALL_SAMPLE_MIN_TASKS = 5

_FAILURE_TAG_DESCRIPTIONS: dict[FailureTag, str] = {
    FailureTag.WRONG_TOOL_CHOICE: (
        "invoked a nonexistent tool, or never used a state-changing tool "
        "on a verifier failure"
    ),
    FailureTag.HALLUCINATED_ELEMENT: "referenced element ids absent from the latest snapshot",
    FailureTag.LOOPING: "repeated identical tool calls verbatim",
    FailureTag.STEP_BUDGET_EXCEEDED_WHILE_PROGRESSING: (
        "ran out of step/time budget while still moving the page forward"
    ),
    FailureTag.STEP_BUDGET_EXCEEDED_STUCK: "burned the budget pushing an unchanged page state",
    FailureTag.TOOL_ERROR_MISHANDLED: "repeated a failing action without adapting to the error",
    FailureTag.PREMATURE_DONE: (
        "SUSPECTED premature done(success=true): claimed done too early, "
        "verifier disagreed"
    ),
    FailureTag.GRACEFUL_GIVE_UP: "agent explicitly declared failure via done(success=false)",
}

_OUTCOME_LABELS: dict[RunOutcome, str] = {
    RunOutcome.SUCCESS: "success",
    RunOutcome.FAILURE_VERIFIER: "failure_verifier (agent finished, verifier disagreed)",
    RunOutcome.FAILURE_MAX_STEPS: "failure_max_steps (step budget exhausted)",
    RunOutcome.FAILURE_TIMEOUT: "failure_timeout (wall-clock budget exhausted)",
    RunOutcome.FAILURE_PROVIDER_ERROR: "failure_provider_error (provider failed after retries)",
    RunOutcome.FAILURE_TOOL_ERROR: "failure_tool_error (browser-tool exception)",
    RunOutcome.FAILURE_CRASH: "failure_crash (unhandled runner exception)",
}


def _pct(rate: float) -> str:
    return f"{rate * 100:.1f}%"


def _cost(value: float | None) -> str:
    return "N/A" if value is None else f"${value:.4f}"


def _seconds(value: float) -> str:
    return f"{value:.2f}s"


def _steps(value: float) -> str:
    return f"{value:.1f}"


# ---------------------------------------------------------------------------
# Honest conclusion — computed from the numbers, never generated by an LLM.
# ---------------------------------------------------------------------------

def build_honest_conclusion(metrics_by_provider: dict[str, TaskSuiteMetrics]) -> list[str]:
    """Programmatically detect "table leader != right choice" divergences.

    Returns Markdown bullet lines. Every sentence is derived from THIS run's
    actual numbers via fixed templates; ties are resolved deterministically
    (alphabetical provider name) so the same data always yields the same text.
    """
    if not metrics_by_provider:
        return ["- Нет данных для вывода: в прогоне не оказалось ни одной метрики."]

    if len(metrics_by_provider) < 2:
        (only,) = metrics_by_provider
        return [
            (
                f"- В прогоне только один провайдер (`{only}`): сравнение "
                "\"лучший результат vs лучший выбор\" требует минимум двух провайдеров."
            ),
        ]

    # Deterministic rankings: value first, name as tie-breaker.
    best_success_name, best_success = min(
        metrics_by_provider.items(),
        key=lambda item: (-item[1].success_rate, item[0]),
    )
    priced = {
        name: m
        for name, m in metrics_by_provider.items()
        if m.avg_cost_usd_per_task is not None
    }
    cheapest_name, cheapest = (
        min(priced.items(), key=lambda item: (item[1].avg_cost_usd_per_task, item[0]))
        if len(priced) >= 2
        else (None, None)
    )
    fastest_name, fastest = min(
        metrics_by_provider.items(),
        key=lambda item: (item[1].p50_latency_seconds, item[0]),
    )

    bpct = _pct(best_success.success_rate)
    lines: list[str] = []

    # Cost divergence: only a real divergence when strictly cheaper than the
    # success-rate leader's own cost (equal costs are not a choice to make).
    if cheapest is not None and cheapest_name != best_success_name:
        assert cheapest is not None and cheapest_name is not None  # for mypy
        best_cost = best_success.avg_cost_usd_per_task
        assert best_cost is not None  # guaranteed: best_success is in `priced`
        cheap_cost = cheapest.avg_cost_usd_per_task
        assert cheap_cost is not None
        if cheap_cost < best_cost:
            savings_pct = (best_cost - cheap_cost) / best_cost * 100
            lines.append(
                f"- Провайдер **{best_success_name}** даёт наивысший общий success rate "
                f"({bpct}), но провайдер **{cheapest_name}** стоит на {savings_pct:.1f}% "
                f"дешевле при success rate {_pct(cheapest.success_rate)}. Выбор зависит "
                "от того, что важнее для конкретного случая использования: максимальное "
                f"качество ({best_success_name}) или минимальная цена ({cheapest_name})."
            )

    # Latency divergence: same strictness rule as for cost.
    if fastest_name != best_success_name and (
        fastest.p50_latency_seconds < best_success.p50_latency_seconds
    ):
        lines.append(
            f"- Провайдер **{best_success_name}** даёт наивысший общий success rate "
            f"({bpct}), но быстрее отвечает провайдер **{fastest_name}**: p50 латентность "
            f"{_seconds(fastest.p50_latency_seconds)} против "
            f"{_seconds(best_success.p50_latency_seconds)}. Если интерактивность важнее "
            f"качества — это аргумент в пользу {fastest_name}."
        )

    if len(priced) < 2:
        lines.append(
            "- Стоимость не сравнивается: менее чем у двух провайдеров есть данные о "
            "ценах (avg cost = N/A). Заполните pricing.yaml, чтобы сравнение цены/качества "
            "стало возможным."
        )

    if not any("Провайдер **" in line for line in lines):
        lines.insert(
            0,
            f"- Провайдер **{best_success_name}** лидирует одновременно по всем "
            f"сравниваемым осям (success rate {_pct(best_success.success_rate)}, цена, "
            "латентность) — расхождений вида \"лучший в таблице ≠ лучший выбор\" "
            "в этом прогоне не обнаружено.",
        )
    return lines


def compute_calibrations(result: SuiteRunResult) -> dict[str, CalibrationReport]:
    """Phase 4 calibration report per provider over this run's traces."""
    by_provider: dict[str, list[RunTrace]] = {}
    for trace in result.traces:
        by_provider.setdefault(trace.provider_name, []).append(trace)
    return {
        provider: compute_calibration_report(traces)
        for provider, traces in sorted(by_provider.items())
    }


def render_report(result: SuiteRunResult) -> str:
    """Render the full six-section Markdown report for one suite run."""
    metrics = result.metrics_by_provider
    providers_sorted = sorted(metrics)
    duration_s = max(0.0, (result.finished_at - result.started_at).total_seconds())
    n_tasks = len({trace.task_id for trace in result.traces})

    lines: list[str] = []
    lines.append("# Agentalyze — Suite Run Report")
    lines.append("")
    lines.append(f"- **Suite run ID:** `{result.suite_run_id}`")
    lines.append(f"- **Дата прогона:** {result.finished_at.astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}")
    lines.append(f"- **Провайдеры:** {', '.join(result.config.provider_names)}")
    lines.append(f"- **Задач в прогоне:** {n_tasks}")
    lines.append(f"- **Общая длительность:** {duration_s:.1f}s")
    lines.append("")
    lines.append("")
    return "\n".join(lines) + _render_remaining_sections(result, providers_sorted)


def _render_remaining_sections(result: SuiteRunResult,
                               providers_sorted: list[str]) -> str:
    sections = [
        *_summary_section(result.metrics_by_provider, providers_sorted),
        "",
        *_categories_section(result, providers_sorted),
        *_failures_section(result, providers_sorted),
        *_calibration_section(result),
        *_honest_conclusion_section(result),
        "",
    ]
    return "\n".join(sections)


def _summary_section(metrics: dict[str, TaskSuiteMetrics],
                     providers_sorted: list[str]) -> list[str]:
    lines = ["## Summary", ""]
    lines.append("| Provider | Tasks | Success rate | Avg cost / task | Avg steps "
                 "| p50 latency | p95 latency |")
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for provider in providers_sorted:
        m = metrics[provider]
        lines.append(
            f"| `{provider}` | {m.total_tasks} | {_pct(m.success_rate)} "
            f"| {_cost(m.avg_cost_usd_per_task)} | {_steps(m.avg_steps_per_task)} "
            f"| {_seconds(m.p50_latency_seconds)} | {_seconds(m.p95_latency_seconds)} |"
        )
    if all(m.avg_cost_usd_per_task is None for m in metrics.values()):
        lines.append("")
        lines.append(
            "> Стоимость `N/A`: для этих провайдеров нет записей в pricing-таблице — "
            "\"неизвестная цена\" не то же самое, что \"бесплатно\"."
        )
    return lines


def _category_table(provider_rows: list[tuple[str, CategoryMetrics]]) -> list[str]:
    lines = ["| Provider | Success rate | Runs failed |", "| --- | ---: | ---: |"]
    for provider, m in provider_rows:
        failures = m.total_tasks - m.success_count
        lines.append(f"| `{provider}` | {_pct(m.success_rate)} | {failures} |")
    return lines


def _categories_section(result: SuiteRunResult,
                        providers_sorted: list[str]) -> list[str]:
    metrics = result.metrics_by_provider
    categories: list[TaskCategory] = []
    for provider in providers_sorted:
        for category in metrics[provider].by_category:
            if category not in categories:
                categories.append(category)

    lines = ["## Breakdown by task category", ""]
    if not categories:
        lines.append("_В трейсах нет информации о категориях задач._")
        return lines

    for category in categories:
        provider_rows = [
            (provider, metrics[provider].by_category[category])
            for provider in providers_sorted
            if category in metrics[provider].by_category
        ]
        task_count = max(m.total_tasks for _, m in provider_rows)
        lines.append(f"### {category.value.upper()} ({task_count} task(s))")
        lines.append("")
        if task_count < SMALL_SAMPLE_MIN_TASKS:
            lines.append(
                f"> ⚠️ **Малая выборка:** в этой категории всего {task_count} задач(и) — "
                "приведённые цифры заметно менее надёжны, чем для категории с 5+ задачами."
            )
            lines.append("")
        lines.extend(_category_table(provider_rows))
        lines.append("")
    return lines


def _failures_section(result: SuiteRunResult, providers_sorted: list[str]) -> list[str]:
    lines = ["## Failure breakdown", ""]
    for provider in providers_sorted:
        traces = [t for t in result.traces if t.provider_name == provider]
        outcome_counts: dict[RunOutcome, int] = {}
        tag_counts: dict[FailureTag, int] = {}
        for trace in traces:
            if trace.outcome is not RunOutcome.SUCCESS:
                outcome_counts[trace.outcome] = outcome_counts.get(trace.outcome, 0) + 1
                for tag in classify_failure(trace):
                    tag_counts[tag] = tag_counts.get(tag, 0) + 1

        lines.append(f"### `{provider}`")
        lines.append("")
        if not outcome_counts:
            lines.append("_Ни одного неуспешного прогона._")
            lines.append("")
            continue

        lines.append("**По исходам (outcome):**")
        lines.append("")
        lines.append("| Outcome | Count |")
        lines.append("| --- | ---: |")
        for outcome in RunOutcome:
            if outcome in outcome_counts:
                lines.append(f"| {_OUTCOME_LABELS[outcome]} | {outcome_counts[outcome]} |")
        lines.append("")

        # Tag counts answer WHY, not just HOW MANY; one run may carry several
        # tags, so tag totals intentionally may exceed the failure count.
        if not tag_counts:
            # A blank table under a "why?" heading would look like a rendering
            # bug and silently suggest "no diagnosable reason"; say plainly
            # that no taxonomy heuristic fired for these failures.
            lines.append(
                "**Почему (failure tags):** ни один из неудачных прогонов этого "
                "провайдера не получил специфических тегов таксономии (например, "
                "все таймауты/бюджеты без зацикливания или повторов ошибок). "
                "Смотрите исходы выше и полные трейсы через `agentbench inspect`."
            )
            lines.append("")
            continue
        lines.append(
            "**Почему (failure tags; один прогон может получить несколько тегов):**"
        )
        lines.append("")
        lines.append("| Tag | Count | Что это значит |")
        lines.append("| --- | ---: | --- |")
        for tag in FailureTag:
            if tag in tag_counts:
                description = _FAILURE_TAG_DESCRIPTIONS[tag].replace("|", "\\|")
                lines.append(f"| `{tag.value}` | {tag_counts[tag]} | {description} |")
        lines.append("")
    return lines


def _calibration_section(result: SuiteRunResult) -> list[str]:
    calibrations = compute_calibrations(result)
    lines = ["## Confidence calibration", ""]
    if not any(c.runs_with_confidence > 0 for c in calibrations.values()):
        lines.append(
            "_Ни один прогон этого suite не сообщил confidence через "
            "`done(..., confidence=...)` — калибровка неприменима._"
        )
        lines.append("")
        return lines

    for provider, calibration in calibrations.items():
        lines.append(f"### `{provider}`")
        lines.append("")
        if (
            calibration.runs_with_confidence == 0
            or calibration.low_statistics_warning is not None
        ):
            # Never print an ECE that Phase 4 itself flagged as statistically
            # meaningless — say so explicitly instead.
            warning = calibration.low_statistics_warning or "нет прогонов с confidence."
            lines.append(f"Недостаточно данных для оценки калибровки: {warning}")
            lines.append("")
            continue

        assert calibration.ece is not None  # guaranteed on the path above
        lines.append(
            f"ECE = **{calibration.ece:.4f}** "
            f"({calibration.runs_with_confidence} прогон(ов) с confidence)."
        )
        lines.append("")
        lines.append("| Bin | Runs | Avg claimed confidence | Observed success rate |")
        lines.append("| --- | ---: | ---: | ---: |")
        for bin_ in calibration.bins:
            if bin_.count == 0:
                continue
            avg_conf = "N/A" if bin_.avg_confidence is None else f"{bin_.avg_confidence:.2f}"
            acc = "N/A" if bin_.success_rate is None else _pct(bin_.success_rate)
            lines.append(
                f"| [{bin_.lower:.1f}, {bin_.upper:.1f}) | {bin_.count} "
                f"| {avg_conf} | {acc} |"
            )
        lines.append("")
    return lines


def _honest_conclusion_section(result: SuiteRunResult) -> list[str]:
    lines = [
        "## Honest conclusion",
        "",
        "_Вычислено программно из чисел этого прогона — без участия языковой модели._",
        "",
    ]
    lines.extend(build_honest_conclusion(result.metrics_by_provider))
    return lines


def generate_report(result: SuiteRunResult, results_dir: Path) -> Path:
    """Render the report and save it to ``{results_dir}/{suite_run_id}/report.md``."""
    path = Path(results_dir) / result.suite_run_id / "report.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(result), encoding="utf-8")
    return path


__all__ = [
    "SMALL_SAMPLE_MIN_TASKS",
    "build_honest_conclusion",
    "compute_calibrations",
    "generate_report",
    "render_report",
]

